title: "Internet Proxy and Connection Settings"
category: "network"
description: "Proxy server configuration, PAC files, automatic proxy detection, and internet connection routing"

paths:
  - "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings"
  - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Internet Settings"
  - "HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\CurrentVersion\\Internet Settings"
  - "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\Connections"

details:
  what: |
    Internet proxy configuration including proxy server addresses, port numbers,
    Proxy Auto-Configuration (PAC) file locations, bypass lists, automatic proxy
    detection settings, and WinINet connection configurations. Controls how web
    browsers and system internet connections route through proxy servers, handle
    authentication, and manage traffic filtering and monitoring.

  forensic_value: |
    Shows proxy configurations that could indicate data exfiltration routes,
    malicious proxy servers used for traffic interception, command and control
    communication, or network evasion techniques. Critical for understanding
    network communication paths, identifying proxy-based attacks, and detecting
    unauthorized network routing that could facilitate data theft.

  structure: |
    Settings include ProxyEnable (proxy enabled/disabled), ProxyServer (address:port),
    ProxyOverride (bypass list), AutoConfigURL (PAC file location), AutoDetect
    (automatic proxy detection), and binary connection data in DefaultConnectionSettings
    containing detailed proxy configurations and authentication information.

  examples:
    - "ProxyEnable: 1 (proxy enabled)"
    - "ProxyServer: 192.168.1.100:8080"
    - "ProxyOverride: localhost;127.*;10.*;192.168.*;*.company.com"
    - "AutoConfigURL: http://proxy.company.com/proxy.pac"
    - "AutoDetect: 1 (automatic proxy detection enabled)"
    - "ProxyServer: socks=127.0.0.1:9050 (SOCKS proxy for Tor)"
    - "ProxyServer: http=proxy.evil.com:3128;https=proxy.evil.com:3128"
    - "MigrateProxy: 1"
    - "EnableHttp1_1: 1"
    - "EnableNegotiate: 1"

  tools:
    - name: "Internet Options"
      description: "Built-in Windows Internet Properties control panel for proxy configuration"
    - name: "Registry Explorer"
      url: "https://ericzimmerman.github.io/#!index.md"
      description: "Advanced registry browser for proxy configuration analysis"
    - name: "ProxyCfg.exe"
      description: "Legacy Windows proxy configuration tool for WinHTTP settings"
    - name: "netsh winhttp"
      description: "Windows HTTP Services proxy configuration utility"
    - name: "ProxyLogView"
      url: "https://www.nirsoft.net/utils/proxy_log_view.html"
      description: "NirSoft tool for proxy server log analysis and monitoring"

metadata:
  windows_versions:
    - "Windows 95"
    - "Windows 98"
    - "Windows NT 4.0"
    - "Windows 2000"
    - "Windows XP"
    - "Windows Vista"
    - "Windows 7"
    - "Windows 8"
    - "Windows 8.1"
    - "Windows 10"
    - "Windows 11"
    - "Windows Server 2000"
    - "Windows Server 2003"
    - "Windows Server 2008"
    - "Windows Server 2012"
    - "Windows Server 2016"
    - "Windows Server 2019"
    - "Windows Server 2022"

  introduced: "Windows 95 (Internet Explorer 3.0)"
  
  criticality: "medium"

  investigation_types:
    - "data-exfiltration"
    - "lateral-movement"
    - "malware-analysis"
    - "incident-response"
    - "behavioral-analysis"

  tags:
    - "network"
    - "proxy"
    - "internet-settings"
    - "pac-files"
    - "traffic-interception"
    - "network-evasion"
    - "command-control"
    - "data-exfiltration"
    - "network-routing"

  references:
    - title: "WinINet Proxy Configuration"
      url: "https://docs.microsoft.com/en-us/windows/win32/wininet/wininet-proxy-configuration"
      type: "official"
    - title: "Proxy Auto-Configuration (PAC) Files"
      url: "https://docs.microsoft.com/en-us/troubleshoot/browsers/proxy-auto-configuration-files"
      type: "official"
    - title: "Network Proxy Security Analysis"
      url: "https://www.sans.org/blog/proxy-configuration-analysis/"
      type: "research"
    - title: "Malware and Proxy Abuse"
      url: "https://www.crowdstrike.com/blog/proxy-based-attacks/"
      type: "research"

  retention:
    default_location: "Registry hives (SOFTWARE, NTUSER.DAT)"
    persistence: "Survives reboots, persists until proxy reconfiguration"
    volatility: "Configuration changes overwrite previous proxy settings"

  related_artifacts:
    - "dns_cache"
    - "network_interfaces"
    - "vpn_connections"
    - "wifi_profiles"
    - "firewall_rules"

author:
  name: "Tonmoy Jitu"
  github: "tonmoy0010"
  x: "tonmoy0010"

contribution:
  date_added: "2025-01-15"
  last_updated: "2025-01-15"
  version: "2.0"