title: "UPnP and Network Discovery Settings"
category: "network"
description: "Universal Plug and Play configuration, network discovery settings, and device enumeration security"

paths:
  - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FolderDescriptions\\{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}"
  - "HKLM\\SYSTEM\\CurrentControlSet\\Services\\upnphost\\Parameters"
  - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Network"
  - "HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\NetworkConnections"

details:
  what: |
    Universal Plug and Play (UPnP) and network discovery configuration controls automatic device
    discovery, network browsing capabilities, network location awareness, and seamless device
    connectivity. Manages device enumeration services, network neighborhood visibility, automatic
    port mapping, and network topology discovery for simplified network device interaction and
    resource sharing in home and enterprise environments.

  forensic_value: |
    Critical for investigating network-based attacks that exploit UPnP vulnerabilities for unauthorized
    access, port manipulation, and lateral movement. UPnP can be abused for network reconnaissance,
    automatic firewall rule creation, and device compromise. Configuration changes may indicate
    attackers enabling network discovery for infrastructure mapping or disabling security features
    that restrict network access and device enumeration capabilities.

  structure: |
    UPnP service configuration includes device discovery settings, network location awareness
    parameters, and browsing capabilities. Network discovery controls visibility of network
    devices and shared resources with settings for public, private, and domain networks.
    FolderDescriptions contains network location definitions and access policies for
    different network profile types.

  examples:
    - "UPnPHost\\Start: 3 (Manual startup - typical configuration)"
    - "NetworkDiscovery: 1 (Network discovery enabled)"
    - "ShowNetworkComputers: 1 (Show network computers in Explorer)"
    - "EnableDeviceAssociation: 1 (Allow automatic device pairing)"
    - "NetworkLocationAwareness: 1 (NLA service active)"
    - "PublicNetworkDiscovery: 0 (Discovery disabled on public networks)"
    - "NC_AllowNetBridge_NLA: 0 (Network bridging restricted)"
    - "UPnP_Enabled: 1 (UPnP framework enabled for applications)"

  tools:
    - name: "Network and Sharing Center"
      description: "Built-in Windows network discovery and sharing management"
    - name: "UPnP Test Tools"
      description: "Network utilities for testing UPnP device discovery and functionality"
    - name: "Registry Explorer"
      url: "https://ericzimmerman.github.io/#!index.md"
      description: "Advanced registry analysis and browsing tool"
    - name: "Network Discovery Settings"
      description: "Windows Control Panel network discovery configuration interface"
    - name: "UPnP Security Scanner"
      description: "Third-party tools for assessing UPnP security vulnerabilities"

metadata:
  windows_versions:
    - "Windows XP"
    - "Windows Vista"
    - "Windows 7"
    - "Windows 8"
    - "Windows 8.1"
    - "Windows 10"
    - "Windows 11"

  introduced: "Windows XP"

  criticality: "medium"

  investigation_types:
    - "lateral-movement"
    - "behavioral-analysis"
    - "incident-response"
    - "timeline-analysis"

  tags:
    - "upnp"
    - "network-discovery"
    - "device-discovery"
    - "network-browsing"
    - "lateral-movement"
    - "network-enumeration"
    - "automatic-configuration"

  references:
    - title: "Microsoft Documentation: UPnP APIs"
      url: "https://docs.microsoft.com/en-us/windows/win32/upnp/universal-plug-and-play-start-page"
      type: "official"
    - title: "UPnP Security Vulnerabilities and Exploitation"
      url: "https://www.sans.org/white-papers/33832/"
      type: "research"

  retention:
    default_location: "Registry hive files (SOFTWARE, SYSTEM)"
    persistence: "Network configuration persists until manually changed"
    volatility: "Network settings affect ongoing device discovery and network security"

  related_artifacts:
    - "network_interfaces"
    - "firewall_rules"
    - "shared_folders"
    - "netbios_settings"

author:
  name: "Tonmoy Jitu"
  github: "tonmoy0010"
  x: "tonmoy0010"

contribution:
  date_added: "2025-01-15"
  last_updated: "2025-01-15"
  version: "2.0"
