title: "BitLocker Drive Encryption Settings"
category: "security"
description: "BitLocker encryption configuration, drive protection status, recovery policies, and TPM integration"

paths:
  - "HKLM\\SOFTWARE\\Policies\\Microsoft\\FVE"
  - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\BitLocker"
  - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\BitLocker"
  - "HKLM\\SYSTEM\\CurrentControlSet\\Services\\BDESVC"

details:
  what: |
    BitLocker Full Volume Encryption manages drive-level encryption configuration including
    encryption algorithms, authentication methods, TPM (Trusted Platform Module) integration,
    recovery key policies, and administrative settings. Controls system drive encryption,
    removable media protection, network unlock capabilities, and enterprise key management
    for comprehensive data protection and compliance requirements.

  forensic_value: |
    Critical for understanding data protection mechanisms that may prevent forensic access,
    reveals encryption bypass attempts, shows evidence of encryption policy violations, and
    indicates security-conscious behavior or attempts to hide data through encryption.
    Configuration changes may reveal insider threats attempting to protect stolen data or
    attackers trying to disable encryption for persistent access.

  structure: |
    BitLocker configuration includes encryption method settings (AES-128/256), authentication
    requirements (TPM, PIN, USB key), recovery options, startup authentication policies,
    and enterprise management settings. Service configuration controls BitLocker Drive
    Encryption Service behavior, automatic encryption, and policy enforcement mechanisms.

  examples:
    - "EncryptionMethod: 3 (AES 128-bit with Diffuser)"
    - "EncryptionMethod: 4 (AES 256-bit with Diffuser)"
    - "UseTPM: 2 (TPM required for system drive)"
    - "UseTPMPIN: 1 (TPM + PIN authentication required)"
    - "UseTPMKey: 0 (USB key not required)"
    - "EnableBDEWithNoTPM: 0 (BitLocker requires TPM)"
    - "RecoveryKeyMessageSource: IT Department Contact: helpdesk@company.com"
    - "BDESVC\\Start: 3 (BitLocker service manual startup)"

  tools:
    - name: "BitLocker Drive Encryption (Control Panel)"
      description: "Built-in Windows BitLocker management interface"
    - name: "manage-bde.exe"
      description: "Command-line BitLocker administration and status utility"
    - name: "Registry Explorer"
      url: "https://ericzimmerman.github.io/#!index.md"
      description: "Advanced registry analysis and browsing tool"
    - name: "Group Policy Editor (gpedit.msc)"
      description: "BitLocker policy configuration and enterprise management"
    - name: "TPM Management Console"
      description: "Trusted Platform Module configuration and monitoring"

metadata:
  windows_versions:
    - "Windows Vista"
    - "Windows 7"
    - "Windows 8"
    - "Windows 8.1"
    - "Windows 10"
    - "Windows 11"
    - "Windows Server 2008"
    - "Windows Server 2012"
    - "Windows Server 2016"
    - "Windows Server 2019"
    - "Windows Server 2022"

  introduced: "Windows Vista"

  criticality: "high"

  investigation_types:
    - "incident-response"
    - "insider-threat"

  tags:
    - "security"
    - "bitlocker"
    - "encryption"
    - "data-protection"
    - "tpm"
    - "drive-encryption"
    - "recovery-keys"
    - "authentication"

  references:
    - title: "Microsoft Documentation: BitLocker"
      url: "https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/"
      type: "official"
    - title: "BitLocker Security and Forensic Considerations"
      url: "https://www.sans.org/white-papers/33649/"
      type: "research"
    - title: "Enterprise BitLocker Management"
      url: "https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-overview"
      type: "official"

  retention:
    default_location: "Registry hive files (SOFTWARE, SYSTEM)"
    persistence: "Encryption settings persist until administratively changed"
    volatility: "Critical security configuration affecting data access and forensic investigations"

  related_artifacts:
    - "security_policy"
    - "tpm_configuration"
    - "recovery_keys"
    - "authentication_methods"

author:
  name: "Tonmoy Jitu"
  github: "tonmoy0010"
  x: "tonmoy0010"

contribution:
  date_added: "2025-06-07"
  last_updated: "2025-06-07"
  version: "1.0"
