title: "SAM Database User Account Information"
category: "security"
description: "Local user account data including password hashes, logon statistics, and account security metadata"

paths:
  - "HKLM\\SAM\\SAM\\Domains\\Account\\Users"
  - "HKLM\\SAM\\SAM\\Domains\\Account\\Users\\Names"
  - "HKLM\\SAM\\SAM\\Domains\\Account\\Aliases"

details:
  what: |
    Security Account Manager (SAM) database stores comprehensive local user account information
    including usernames, NTLM password hashes, account policies, logon counts, last logon times,
    password change dates, account lockout information, group memberships, and security metadata.
    Manages local authentication credentials, account restrictions, and user privilege assignments
    for complete local user account security and authentication management.

  forensic_value: |
    Critical for identifying unauthorized accounts, password attack evidence, account creation
    timelines, and authentication patterns during security incidents. Password hashes enable
    offline password cracking for credential recovery, privilege escalation analysis, and
    unauthorized access investigations. Essential for insider threat investigations, privilege
    escalation analysis, and determining account compromise through authentication anomalies.

  structure: |
    User accounts organized by Relative Identifier (RID) starting from 500 for built-in accounts.
    Binary data structures contain NTLM password hashes, account creation timestamps, last logon
    times, logon counts, bad password attempts, account flags, and security descriptors.
    Names subkey provides RID-to-username mappings for account identification and correlation.

  examples:
    - "RID 500: Built-in Administrator account (Default system administrator)"
    - "RID 1001: Local user account (First user-created account)"
    - "Username: administrator (Account name in Names subkey)"
    - "NTLM Hash: aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0"
    - "Last Logon: 2024-01-15 14:30:25 UTC (Most recent authentication)"
    - "Password Last Set: 2024-01-01 08:00:00 UTC (Password change timestamp)"
    - "Logon Count: 157 (Total successful authentications)"
    - "Bad Password Count: 3 (Failed authentication attempts)"

  tools:
    - name: "SAMInside"
      description: "Professional SAM database analysis and password recovery tool"
    - name: "pwdump"
      description: "Command-line tool for extracting password hashes from SAM database"
    - name: "John the Ripper"
      url: "https://www.openwall.com/john/"
      description: "Advanced password cracking tool for hash analysis"
    - name: "Ophcrack"
      url: "https://ophcrack.sourceforge.io/"
      description: "Rainbow table-based password cracking utility"
    - name: "Registry Explorer"
      url: "https://ericzimmerman.github.io/#!index.md"
      description: "Advanced registry analysis and browsing tool"

metadata:
  windows_versions:
    - "Windows NT"
    - "Windows 2000"
    - "Windows XP"
    - "Windows Vista"
    - "Windows 7"
    - "Windows 8"
    - "Windows 8.1"
    - "Windows 10"
    - "Windows 11"
    - "Windows Server 2000"
    - "Windows Server 2003"
    - "Windows Server 2008"
    - "Windows Server 2012"
    - "Windows Server 2016"
    - "Windows Server 2019"
    - "Windows Server 2022"

  introduced: "Windows NT 3.1"

  criticality: "high"

  investigation_types:
    - "lateral-movement"
    - "incident-response"
    - "timeline-analysis"
    - "privilege-escalation"

  tags:
    - "security"
    - "user-accounts"
    - "password-hashes"
    - "authentication"
    - "account-creation"
    - "sam-database"
    - "credential-analysis"

  references:
    - title: "Microsoft Documentation: Security Account Manager"
      url: "https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/"
      type: "official"
    - title: "SAM Database Forensics and Analysis"
      url: "https://www.sans.org/white-papers/36427/"
      type: "research"
    - title: "Windows Authentication and Credential Analysis"
      url: "https://attack.mitre.org/techniques/T1003/002/"
      type: "research"

  retention:
    default_location: "Registry hive files (SAM)"
    persistence: "Account data persists until account deletion or system reinstallation"
    volatility: "Authentication data provides immediate evidence of credential compromise"

  related_artifacts:
    - "security_policy"
    - "user_profiles"
    - "event_log_config"
    - "lsa_packages"

author:
  name: "Tonmoy Jitu"
  github: "tonmoy0010"
  x: "tonmoy0010"

contribution:
  date_added: "2025-01-15"
  last_updated: "2025-01-15"
  version: "2.0"
