title: "Windows Defender and Security Configuration"
category: "security"
description: "Windows Defender settings, exclusions, security policies, and threat protection configuration"

paths:
  - "HKLM\\SOFTWARE\\Microsoft\\Windows Defender"
  - "HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender"
  - "HKCU\\SOFTWARE\\Microsoft\\Windows Defender"
  - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System"
  - "HKLM\\SOFTWARE\\Microsoft\\Windows Security Health\\State"

details:
  what: |
    Windows Defender (Windows Security) configuration including real-time protection
    settings, scan exclusions, threat detection policies, User Account Control (UAC)
    settings, and security feature states. Controls system security posture, malware
    detection capabilities, and security policy enforcement mechanisms.

  forensic_value: |
    Shows if security features were disabled to facilitate malware execution,
    reveals exclusion paths that attackers may have added, and indicates
    security policy modifications. Critical for understanding security bypass techniques,
    identifying potential compromise indicators, and assessing security posture during incidents.

  structure: |
    Defender settings include DisableAntiSpyware, DisableRealtimeMonitoring,
    scan exclusions, update configurations, and threat response settings. UAC settings 
    control elevation prompts and administrator approval mode. Binary policy data
    controls feature enablement and security enforcement levels.

  examples:
    - "DisableAntiSpyware: 1 (Windows Defender disabled)"
    - "DisableRealtimeMonitoring: 1 (Real-time protection off)"
    - "ExclusionPath: C:\\Malware\\staging"
    - "ExclusionProcess: suspicious.exe"
    - "EnableLUA: 0 (UAC completely disabled)"
    - "ConsentPromptBehaviorAdmin: 0 (No UAC prompts)"
    - "ThreatSeverityDefaultAction: 6 (Allow all threats)"
    - "SubmitSamplesConsent: 2 (Never send samples)"

  tools:
    - name: "Windows Security"
      description: "Built-in Windows security management interface"
    - name: "Get-MpPreference PowerShell"
      description: "PowerShell cmdlet for Windows Defender configuration analysis"
    - name: "Registry Explorer"
      url: "https://ericzimmerman.github.io/#!index.md"
      description: "Advanced registry analysis for security configuration review"
    - name: "Group Policy Editor"
      description: "Windows Group Policy management for security policy analysis"
    - name: "Windows Defender Configuration Analyzer"
      description: "Custom tools for security configuration assessment"

metadata:
  windows_versions:
    - "Windows Vista"
    - "Windows 7"
    - "Windows 8"
    - "Windows 8.1"
    - "Windows 10"
    - "Windows 11"
    - "Windows Server 2008"
    - "Windows Server 2012"
    - "Windows Server 2016"
    - "Windows Server 2019"
    - "Windows Server 2022"

  introduced: "Windows Vista (as Windows Defender)"
  
  criticality: "high"

  investigation_types:
    - "malware-analysis"
    - "incident-response"
    - "behavioral-analysis"
    - "persistence-analysis"

  tags:
    - "security"
    - "windows-defender"
    - "antivirus"
    - "security-policy"
    - "uac"
    - "malware-evasion"
    - "exclusions"
    - "threat-protection"
    - "security-bypass"

  references:
    - title: "Windows Defender Antivirus Management"
      url: "https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/"
      type: "official"
    - title: "User Account Control Security"
      url: "https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/"
      type: "official"
    - title: "MITRE ATT&CK: Disable or Modify Tools"
      url: "https://attack.mitre.org/techniques/T1562/001/"
      type: "research"
    - title: "Windows Security Configuration Analysis"
      url: "https://www.sans.org/blog/windows-security-configuration-analysis/"
      type: "research"

  retention:
    default_location: "Registry hives (SOFTWARE, SYSTEM)"
    persistence: "Survives reboots, persists until policy changes or reinstallation"
    volatility: "Configuration changes overwrite previous settings, audit logs may retain history"

  related_artifacts:
    - "security_policy"
    - "applocker_policies"
    - "software_restriction"
    - "event_log_config"
    - "security_center"

author:
  name: "Tonmoy Jitu"
  github: "tonmoy0010"
  x: "tonmoy0010"

contribution:
  date_added: "2025-01-15"
  last_updated: "2025-01-15"
  version: "2.0"