title: "Event Log Configuration and Settings"
category: "system"
description: "Windows Event Log size limits, retention policies, enabled/disabled logging channels, and audit configuration"

paths:
  - "HKLM\\SYSTEM\\CurrentControlSet\\Services\\EventLog"
  - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels"
  - "HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\EventLog"
  - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\Audit"

details:
  what: |
    Windows stores comprehensive event log configuration including maximum log sizes, retention policies,
    enabled/disabled channels, log file locations, access permissions, and audit policy settings.
    Controls logging behavior for Security, Application, System, Setup, and custom event logs including
    modern Windows Event Log (EVTX) channels and legacy event log format settings.

  forensic_value: |
    Critical for forensic investigations as it reveals if attackers disabled logging to hide malicious
    activity, modified log retention to prevent evidence preservation, or altered audit policies to
    avoid detection. Shows evidence tampering attempts, insufficient logging configurations that may
    result in missing evidence, and indicates security-conscious modifications that affect investigation
    capabilities and timeline reconstruction.

  structure: |
    EventLog service configuration includes log names as subkeys containing MaxSize (maximum bytes),
    Retention (retention days), File (log file path), RestrictGuestAccess (access permissions),
    and Sources (event sources). WINEVT Channels contain modern event log configuration with
    Enabled status, Isolation levels, Access permissions, and MaxSize settings stored as various data types.

  examples:
    - "Security\\MaxSize: 0x6400000 (100MB maximum log size)"
    - "Security\\Retention: 0 (overwrite events as needed)"
    - "Application\\File: %SystemRoot%\\System32\\Winevt\\Logs\\Application.evtx"
    - "Microsoft-Windows-PowerShell/Operational\\Enabled: 0 (PowerShell logging disabled)"
    - "Security\\RestrictGuestAccess: 1 (guest access restricted)"
    - "Microsoft-Windows-Sysmon/Operational\\MaxSize: 0x40000000 (1GB Sysmon log)"
    - "System\\AutoBackupLogFiles: 1 (automatic log backup enabled)"
    - "AuditLogonEvents: 0 (logon auditing disabled)"

  tools:
    - name: "Event Viewer (eventvwr.msc)"
      description: "Built-in Windows event log viewer and configuration interface"
    - name: "wevtutil.exe"
      description: "Command-line event log configuration and management utility"
    - name: "Registry Explorer"
      url: "https://ericzimmerman.github.io/#!index.md"
      description: "Advanced registry analysis and browsing tool"
    - name: "LogParser"
      url: "https://www.microsoft.com/en-us/download/details.aspx?id=24659"
      description: "Powerful log analysis and query tool"
    - name: "Get-WinEvent PowerShell"
      description: "PowerShell cmdlets for event log analysis and configuration"
    - name: "Event Log Explorer"
      url: "https://eventlogxp.com/"
      description: "Advanced event log analysis and management tool"

metadata:
  windows_versions:
    - "Windows NT"
    - "Windows 2000"
    - "Windows XP"
    - "Windows Vista"
    - "Windows 7"
    - "Windows 8"
    - "Windows 8.1"
    - "Windows 10"
    - "Windows 11"
    - "Windows Server 2000"
    - "Windows Server 2003"
    - "Windows Server 2008"
    - "Windows Server 2012"
    - "Windows Server 2016"
    - "Windows Server 2019"
    - "Windows Server 2022"

  introduced: "Windows NT 3.1"

  criticality: "high"

  investigation_types:
    - "incident-response"
    - "malware-analysis"
    - "timeline-analysis"

  tags:
    - "event-logs"
    - "logging-config"
    - "audit-policy"
    - "evidence-tampering"
    - "log-retention"
    - "security-logging"
    - "winevt"
    - "sysmon"

  references:
    - title: "Microsoft Documentation: Windows Event Logging"
      url: "https://docs.microsoft.com/en-us/windows/win32/eventlog/event-logging"
      type: "official"
    - title: "Windows Event Log Analysis for Incident Response"
      url: "https://www.sans.org/white-papers/32949/"
      type: "research"
    - title: "Advanced Windows Event Log Forensics"
      url: "https://www.forensicfocus.com/articles/advanced-windows-event-log-forensics/"
      type: "research"

  retention:
    default_location: "Registry hive files (SYSTEM, SOFTWARE), event log files"
    persistence: "Configuration settings persist until manually changed"
    volatility: "Critical settings that affect all future evidence collection and analysis"

  related_artifacts:
    - "security_policy"
    - "audit_settings"
    - "windows_defender"
    - "performance_monitoring"

author:
  name: "Tonmoy Jitu"
  github: "tonmoy0010"
  x: "tonmoy0010"

contribution:
  date_added: "2025-01-15"
  last_updated: "2025-01-15"
  version: "2.0"
