title: "SAM Database User Account Information"
category: "system"
description: "Local user account data including password hashes, logon counts, account policies, and authentication history"

paths:
  - "HKLM\\SAM\\SAM\\Domains\\Account\\Users"
  - "HKLM\\SAM\\SAM\\Domains\\Account\\Users\\Names"
  - "HKLM\\SAM\\SAM\\Domains\\Account\\Aliases"
  - "HKLM\\SAM\\SAM\\Domains\\Builtin\\Aliases"

details:
  what: |
    Security Account Manager (SAM) database stores comprehensive local user account information 
    including usernames, password hashes (NTLM), account policies, logon counts, last logon times,
    password change dates, account lockout information, and group memberships. Contains both
    active and disabled accounts with detailed authentication history and security settings.
    Critical component of Windows local authentication infrastructure.

  forensic_value: |
    Critical for identifying unauthorized accounts, password attacks, account creation timelines,
    and user authentication patterns. Password hashes can be cracked or used for pass-the-hash
    attacks. Shows evidence of account compromise, privilege escalation, lateral movement, and
    unauthorized access attempts. Essential for user timeline analysis and security assessment.

  structure: |
    User accounts stored by Relative Identifier (RID) starting from 500 (Administrator).
    Contains binary data structures with NTLM password hashes, FILETIME timestamps for
    account creation/last logon/password changes, logon count, bad password count, account
    flags, and group membership information. Names subkey provides RID to username mapping.

  examples:
    - "RID 500: Built-in Administrator account"
    - "RID 1001: Local user account (first created user)"
    - "Username: administrator"
    - "NTLM Hash: aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0"
    - "Last Logon: 2024-01-15 14:30:25 UTC"
    - "Password Last Set: 2024-01-01 08:00:00 UTC"
    - "Account Created: 2023-12-15 10:00:00 UTC"
    - "Logon Count: 157"
    - "Bad Password Count: 3"
    - "Account Flags: 0x0210 (Normal user, password never expires)"

  tools:
    - name: "SAMInside"
      url: "https://www.insidepro.com/saminside.php"
      description: "Professional SAM database analysis and password recovery tool"
    - name: "pwdump7"
      url: "https://www.tarasco.org/security/pwdump_7/"
      description: "Tool for extracting password hashes from SAM database"
    - name: "Ophcrack"
      url: "https://ophcrack.sourceforge.io/"
      description: "Rainbow table-based password cracking tool for Windows"
    - name: "John the Ripper"
      url: "https://www.openwall.com/john/"
      description: "Advanced password cracking tool with Windows hash support"
    - name: "Registry Explorer"
      url: "https://ericzimmerman.github.io/#!index.md"
      description: "Advanced registry browser with SAM analysis capabilities"
    - name: "SAM Parser"
      description: "Specialized tools for SAM database structure analysis"

metadata:
  windows_versions:
    - "Windows NT 3.1"
    - "Windows NT 3.5"
    - "Windows NT 4.0"
    - "Windows 2000"
    - "Windows XP"
    - "Windows Vista"
    - "Windows 7"
    - "Windows 8"
    - "Windows 8.1"
    - "Windows 10"
    - "Windows 11"
    - "Windows Server 2003"
    - "Windows Server 2008"
    - "Windows Server 2012"
    - "Windows Server 2016"
    - "Windows Server 2019"
    - "Windows Server 2022"

  introduced: "Windows NT 3.1"
  
  criticality: "high"

  investigation_types:
    - "privilege-escalation"
    - "lateral-movement"
    - "incident-response"
    - "timeline-analysis"
    - "malware-analysis"

  tags:
    - "system"
    - "user-accounts"
    - "password-hashes"
    - "authentication"
    - "account-creation"
    - "security"
    - "privilege-escalation"
    - "ntlm-hashes"
    - "logon-history"
    - "account-policy"

  references:
    - title: "Security Account Manager (SAM)"
      url: "https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-audit-account-management"
      type: "official"
    - title: "Windows Authentication Architecture"
      url: "https://docs.microsoft.com/en-us/windows-server/security/windows-authentication/windows-authentication-architecture"
      type: "official"
    - title: "MITRE ATT&CK: Account Discovery"
      url: "https://attack.mitre.org/techniques/T1087/001/"
      type: "research"
    - title: "Windows SAM Database Analysis"
      url: "https://www.sans.org/blog/digital-forensics-sam-analysis/"
      type: "research"

  retention:
    default_location: "SAM registry hive (%SystemRoot%\\System32\\config\\SAM)"
    persistence: "Survives reboots, persists until account deletion or system reinstallation"
    volatility: "Account data persistent but logon history may be limited by policy settings"

  related_artifacts:
    - "user_profiles"
    - "security_policy"
    - "event_log_config"
    - "winlogon_userinit"
    - "lsa_packages"

author:
  name: "Tonmoy Jitu"
  github: "tonmoy0010"
  x: "tonmoy0010"

contribution:
  date_added: "2025-01-15"
  last_updated: "2025-01-15"
  version: "2.0"