title: "Time Zone and Clock Configuration"
category: "system"
description: "System time zone settings, NTP configuration, daylight saving time policies, and time synchronization"

paths:
  - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\TimeZoneInformation"
  - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\DateTime\\Servers"
  - "HKLM\\SYSTEM\\CurrentControlSet\\Services\\W32Time"
  - "HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Time Service"

details:
  what: |
    Windows time and date configuration encompasses time zone settings, Network Time Protocol (NTP)
    server configuration, daylight saving time policies, automatic time synchronization settings,
    and time service behavior. Controls system clock accuracy, timezone conversions, automatic
    daylight saving adjustments, and network time synchronization for accurate timeline
    reconstruction and system correlation across different geographic locations.

  forensic_value: |
    Critical for forensic timeline analysis, correlation with other systems, and understanding
    actual event timing. Time zone modifications may indicate attempts to obscure activity
    timing, manipulate log timestamps, or hide temporal correlations. Essential for accurate
    timeline reconstruction, cross-system correlation, and detecting time-based anti-forensic
    techniques used to confuse investigators about actual event timing.

  structure: |
    TimeZoneInformation contains StandardName (timezone), DaylightName (DST name), Bias (UTC offset),
    StandardBias and DaylightBias (offset adjustments), and transition dates. W32Time service
    controls NTP client/server behavior, synchronization intervals, and time source hierarchy.
    DateTime\\Servers maintains time server lists and synchronization preferences.

  examples:
    - "StandardName: Pacific Standard Time (West Coast US timezone)"
    - "DaylightName: Pacific Daylight Time (DST designation)"
    - "Bias: 480 (UTC-8, 480 minutes behind UTC)"
    - "StandardBias: 0 (No additional offset for standard time)"
    - "DaylightBias: -60 (1 hour ahead during daylight saving)"
    - "NtpServer: time.windows.com,0x9 (Microsoft time server)"
    - "UpdateInterval: 604800 (Weekly synchronization)"
    - "W32Time\\Type: NTP (Network Time Protocol client)"

  tools:
    - name: "Date and Time Settings (timedate.cpl)"
      description: "Built-in Windows time and timezone configuration interface"
    - name: "w32tm.exe"
      description: "Windows Time service command-line configuration utility"
    - name: "Registry Explorer"
      url: "https://ericzimmerman.github.io/#!index.md"
      description: "Advanced registry analysis and browsing tool"
    - name: "Time Zone Analyzer"
      description: "Forensic tools for analyzing time zone changes and timeline correlation"
    - name: "NTP Configuration Tools"
      description: "Network time protocol configuration and monitoring utilities"

metadata:
  windows_versions:
    - "Windows NT"
    - "Windows 2000"
    - "Windows XP"
    - "Windows Vista"
    - "Windows 7"
    - "Windows 8"
    - "Windows 8.1"
    - "Windows 10"
    - "Windows 11"
    - "Windows Server 2000"
    - "Windows Server 2003"
    - "Windows Server 2008"
    - "Windows Server 2012"
    - "Windows Server 2016"
    - "Windows Server 2019"
    - "Windows Server 2022"

  introduced: "Windows NT 3.1"

  criticality: "medium"

  investigation_types:
    - "timeline-analysis"
    - "incident-response"
    - "behavioral-analysis"

  tags:
    - "system"
    - "timezone"
    - "time-synchronization"
    - "ntp"
    - "timeline-analysis"
    - "clock-settings"
    - "daylight-saving"
    - "temporal-correlation"

  references:
    - title: "Microsoft Documentation: Windows Time Service"
      url: "https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/"
      type: "official"
    - title: "Time Zone Forensics and Timeline Analysis"
      url: "https://www.sans.org/white-papers/33927/"
      type: "research"
    - title: "Digital Forensics: Time and Date Analysis"
      url: "https://www.forensicfocus.com/articles/time-date-forensics/"
      type: "research"

  retention:
    default_location: "Registry hive files (SYSTEM, SOFTWARE)"
    persistence: "Time zone settings persist until manually changed"
    volatility: "Critical for accurate timestamp interpretation and timeline reconstruction"

  related_artifacts:
    - "version_info"
    - "computer_name"
    - "event_log_config"
    - "regional_settings"

author:
  name: "Tonmoy Jitu"
  github: "tonmoy0010"
  x: "tonmoy0010"

contribution:
  date_added: "2025-06-07"
  last_updated: "2025-06-07"
  version: "1.0"
