title: "Windows Services Configuration and Execution"
category: "execution"
description: "Windows service definitions, startup configurations, dependencies, and service-based persistence mechanisms"

paths:
  - "HKLM\\SYSTEM\\CurrentControlSet\\Services"
  - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\ServiceGroupOrder"
  - "HKLM\\SYSTEM\\CurrentControlSet\\Control\\GroupOrderList"
  - "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Svchost"

details:
  what: |
    Windows Services registry contains comprehensive service configuration including executable
    paths, startup types, dependencies, security descriptors, service accounts, group memberships,
    and failure recovery actions. Controls system service behavior, automatic startup sequences,
    service isolation, and inter-service dependencies for complete Windows service management
    and execution control across system and user contexts.

  forensic_value: |
    Critical for identifying malicious service installation, service hijacking attacks, and
    unauthorized service modifications used for persistence. Shows evidence of malware services,
    suspicious service configurations, privilege escalation through service accounts, and
    service-based backdoors. Essential for detecting advanced persistent threats that abuse
    legitimate service infrastructure for stealth and persistence.

  structure: |
    Individual service subkeys contain ImagePath (executable), Start (startup type), Type
    (service type), ObjectName (service account), DependOnService (dependencies), and
    ServiceSidType (security identifier type). Svchost configuration manages service
    hosting for shared processes with isolation and security boundaries.

  examples:
    - "Services\\MaliciousService\\ImagePath: C:\\malware\\backdoor.exe"
    - "Services\\Spooler\\Start: 2 (Automatic startup)"
    - "Services\\BITS\\Type: 32 (Win32 service, share process)"
    - "Services\\TrustedInstaller\\ObjectName: NT SERVICE\\TrustedInstaller"
    - "Services\\Themes\\DependOnService: RpcSs (RPC dependency)"
    - "Svchost\\netsvcs: BITS,Themes,Schedule,ProfSvc (Service group)"
    - "Services\\BackdoorSvc\\FailureActions: [Binary recovery settings]"
    - "Services\\SuspiciousSvc\\ServiceSidType: 1 (Unrestricted service SID)"

  tools:
    - name: "Services Management Console (services.msc)"
      description: "Built-in Windows service management and configuration interface"
    - name: "sc.exe"
      description: "Service Control command-line utility for service management"
    - name: "Registry Explorer"
      url: "https://ericzimmerman.github.io/#!index.md"
      description: "Advanced registry analysis and browsing tool"
    - name: "Autoruns"
      url: "https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns"
      description: "Microsoft Sysinternals comprehensive service enumeration tool"
    - name: "Service Security Analyzer"
      description: "Tools for analyzing service security configurations and permissions"

metadata:
  windows_versions:
    - "Windows NT 3.1"
    - "Windows NT 4.0"
    - "Windows 2000"
    - "Windows XP"
    - "Windows Vista"
    - "Windows 7"
    - "Windows 8"
    - "Windows 8.1"
    - "Windows 10"
    - "Windows 11"
    - "Windows Server 2003"
    - "Windows Server 2008"
    - "Windows Server 2012"
    - "Windows Server 2016"
    - "Windows Server 2019"
    - "Windows Server 2022"

  introduced: "Windows NT 3.1"

  criticality: "high"

  investigation_types:
    - "malware-analysis"
    - "persistence-analysis"
    - "privilege-escalation"
    - "incident-response"
    - "behavioral-analysis"

  tags:
    - "execution"
    - "windows-services"
    - "persistence"
    - "privilege-escalation"
    - "service-hijacking"
    - "malware-services"
    - "system-services"
    - "service-accounts"

  references:
    - title: "Microsoft Documentation: Windows Services"
      url: "https://docs.microsoft.com/en-us/windows/win32/services/services"
      type: "official"
    - title: "MITRE ATT&CK: Windows Service"
      url: "https://attack.mitre.org/techniques/T1543/003/"
      type: "research"
    - title: "Windows Service Security Analysis"
      url: "https://www.sans.org/white-papers/36240/"
      type: "research"

  retention:
    default_location: "SYSTEM registry hive"
    persistence: "Service configuration persists until service removal or modification"
    volatility: "Service settings control ongoing system behavior and security posture"

  related_artifacts:
    - "registry_run_keys"
    - "scheduled_tasks"
    - "winlogon_userinit"
    - "startup_programs"
    - "lsa_packages"

author:
  name: "Tonmoy Jitu"
  github: "tonmoy0010"
  x: "tonmoy0010"

contribution:
  date_added: "2025-01-15"
  last_updated: "2025-01-15"
  version: "2.0"