title: "Windows Script Host Settings and Configuration"
category: "program-execution"
description: "Windows Script Host execution policies, script engine settings, and VBScript/JScript security configuration"

paths:
  - "HKLM\\SOFTWARE\\Microsoft\\Windows Script Host\\Settings"
  - "HKCU\\SOFTWARE\\Microsoft\\Windows Script Host\\Settings"
  - "HKLM\\SOFTWARE\\Classes\\VBSFile\\Shell\\Open\\Command"
  - "HKLM\\SOFTWARE\\Classes\\JSFile\\Shell\\Open\\Command"

details:
  what: |
    Windows Script Host (WSH) provides native scripting capabilities for VBScript and JScript execution 
    with security and execution policy configuration. Controls script execution permissions, timeout settings, 
    security zones, debugging capabilities, and engine-specific behaviors for both system-wide and user-specific contexts.

  forensic_value: |
    Critical for detecting script-based malware attacks, policy bypass attempts, and unauthorized script execution. 
    Shows if WSH was disabled to prevent malicious script execution or enabled to facilitate attacks. 
    Configuration changes may indicate attempts to execute malicious VBScript or JScript files, bypass security 
    restrictions, or establish script-based persistence mechanisms.

  structure: |
    WSH configuration includes Enabled (global WSH enablement), Timeout (script execution timeout), 
    DisplayLogo (banner display), TrustPolicy (script trust level), and UseWINSAFER (Windows SAFER integration). 
    Settings control script engine behavior, security restrictions, and debugging capabilities stored as REG_DWORD values.

  examples:
    - "Enabled: 0 (Windows Script Host completely disabled)"
    - "Enabled: 1 (WSH enabled for script execution)"
    - "Timeout: 0 (No timeout limit for script execution)"
    - "DisplayLogo: 0 (Suppress WSH banner when scripts run)"
    - "TrustPolicy: 0 (Allow all scripts to run)"
    - "TrustPolicy: 2 (Disallow all scripts - high security)"
    - "UseWINSAFER: 1 (Integrate with Software Restriction Policies)"
    - "Remote: 0 (Disable remote WSH execution)"

  tools:
    - name: "cscript.exe / wscript.exe"
      description: "Built-in Windows Script Host command-line and Windows-based script engines"
    - name: "Group Policy Editor (gpedit.msc)"
      description: "Configure WSH policies through Administrative Templates"
    - name: "Registry Explorer"
      url: "https://ericzimmerman.github.io/#!index.md"
      description: "Advanced registry analysis and browsing tool"
    - name: "Script Security Scanner"
      description: "Third-party tools for analyzing WSH security configuration"
    - name: "Windows Script Host Analysis Tools"
      description: "Specialized utilities for WSH configuration assessment"

limitations:
  - "WSH disable settings do NOT prevent script execution - can be bypassed with cscript.exe //B parameter"
  - "Scripts can be executed directly through script engines bypassing WSH settings"
  - "Third-party script interpreters ignore WSH configuration settings"
  - "PowerShell and other scripting engines operate independently of WSH policies"
  - "Malicious scripts may modify WSH settings to enable execution"
  - "Administrative privileges can override user-level WSH restrictions"
  - "WSH settings may be reset by Windows updates or system restoration"
  - "Remote script execution settings may not apply to all script delivery methods"

correlation:
  required_for_definitive_execution_proof:
    - "Process execution logs showing cscript.exe or wscript.exe launches with script parameters"
    - "Script file system artifacts showing VBScript or JScript files accessed or executed"
    - "Application event logs showing script engine activity and execution results"
    - "Command-line history showing script execution commands"
    
  strengthens_evidence:
    - "File modifications created by script execution"
    - "Network connections initiated by script processes"
    - "Registry modifications made by executed scripts"
    - "Scheduled tasks containing script-based automation"

metadata:
  windows_versions:
    - "Windows 98"
    - "Windows 2000"
    - "Windows XP"
    - "Windows Vista"
    - "Windows 7"
    - "Windows 8"
    - "Windows 8.1"
    - "Windows 10"
    - "Windows 11"
    - "Windows Server 2000"
    - "Windows Server 2003"
    - "Windows Server 2008"
    - "Windows Server 2012"
    - "Windows Server 2016"
    - "Windows Server 2019"
    - "Windows Server 2022"

  introduced: "Windows 98"
  criticality: "high"

  investigation_types:
    - "malware-analysis"
    - "incident-response"
    - "behavioral-analysis"
    - "persistence-analysis"
    - "program-execution"

  tags:
    - "script-execution"
    - "vbscript"
    - "jscript"
    - "wsh"
    - "script-security"
    - "execution-policy"
    - "malware-delivery"
    - "fileless-attacks"

  references:
    - title: "Microsoft Documentation: Windows Script Host"
      url: "https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc738350(v=ws.10)"
      type: "official"
    - title: "Windows Script Host Security"
      url: "https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc976135(v=technet.10)"
      type: "official"
    - title: "MITRE ATT&CK: Windows Script Host"
      url: "https://attack.mitre.org/techniques/T1059/005/"
      type: "research"
    - title: "Script-Based Attack Detection and Analysis"
      url: "https://www.sans.org/white-papers/36240/"
      type: "research"

  retention:
    default_location: "Registry hive files (SOFTWARE, NTUSER.DAT)"
    persistence: "Script execution settings persist until manually changed or policy override"
    volatility: "Configuration changes affect immediate script execution capabilities and security posture"

  related_artifacts:
    - "powershell_policy"
    - "file_associations"
    - "software_restriction"
    - "applocker_policies"
    - "security_policy"

author:
  name: "Tonmoy Jitu"
  github: "tonmoy0010"
  x: "tonmoy0010"

contribution:
  date_added: "2025-01-15"
  last_updated: "2025-06-12"
  version: "3.0"
