title: "Common Dialog Settings and File Browser History"
category: "user-activity"
description: "File dialog preferences, view settings, browsing behavior configuration, and dialog customization"

paths:
  - "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ComDlg32\\CIDSizeMRU"
  - "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ComDlg32\\LastVisitedMRU"
  - "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ComDlg32\\PlacesBar"
  - "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ComDlg32\\FirstFolder"

details:
  what: |
    Common file dialog configuration encompasses window sizing preferences, last visited folders,
    custom places bar shortcuts, initial folder settings, and file browser behavior across
    different applications and file operation contexts. Manages user interface customization,
    navigation preferences, and application-specific dialog settings for consistent user
    experience across Windows applications and improved workflow efficiency.

  forensic_value: |
    Provides detailed insights into user interaction patterns with file dialogs across multiple
    applications, reveals preferred locations for file operations, shows evidence of file access
    behaviors and workflow patterns. Critical for understanding user navigation habits, establishing
    application usage patterns, and correlating file access activities with specific user
    intentions and operational contexts throughout various software applications.

  structure: |
    CIDSizeMRU stores dialog sizing information organized by application executable names.
    LastVisitedMRU maintains recent folder navigation history for file operations. PlacesBar
    contains custom shortcuts displayed in file dialogs. FirstFolder tracks default starting
    locations for different file types and applications with binary PIDL data structures.

  examples:
    - "CIDSizeMRU\\\\notepad.exe: Dialog window size 800x600 (Notepad file dialog preferences)"
    - "CIDSizeMRU\\\\winword.exe: Microsoft Word dialog sizing information"
    - "LastVisitedMRU\\\\exe files: C:\\\\Tools\\\\Utilities (Executable file access location)"
    - "PlacesBar\\\\Place0: Desktop (Custom shortcut in file dialog)"
    - "PlacesBar\\\\Place1: C:\\\\Users\\\\user\\\\Documents (Quick access folder)"
    - "PlacesBar\\\\Place2: \\\\\\\\server\\\\shared (Network location shortcut)"
    - "FirstFolder\\\\*.pdf: C:\\\\Downloads (Default PDF file location)"

  tools:
    - name: "File Dialog Customization Tools"
      description: "Third-party utilities for analyzing and customizing file dialog behavior"
    - name: "Registry Explorer"
      url: "https://ericzimmerman.github.io/#!index.md"
      description: "Advanced registry analysis and browsing tool"
    - name: "Common Dialog Parser"
      description: "Specialized tools for analyzing Windows common dialog registry data"
    - name: "RegRipper"
      url: "https://github.com/keydet89/RegRipper3.0"
      description: "Registry data extraction and analysis framework"
    - name: "PIDL Analyzer"
      description: "Tools for decoding Windows Shell Item Lists and folder references"

metadata:
  windows_versions:
    - "Windows 95"
    - "Windows NT"
    - "Windows XP"
    - "Windows Vista"
    - "Windows 7"
    - "Windows 8"
    - "Windows 8.1"
    - "Windows 10"
    - "Windows 11"

  introduced: "Windows 95"

  criticality: "low"

  investigation_types:
    - "behavioral-analysis"
    - "insider-threat"
    - "incident-response"
    - "timeline-analysis"

  tags:
    - "file-dialogs"
    - "browsing-behavior"
    - "dialog-preferences"
    - "folder-navigation"
    - "places-bar"
    - "user-interface"
    - "application-settings"

  references:
    - title: "Microsoft Documentation: Common Dialog Box Library"
      url: "https://docs.microsoft.com/en-us/windows/win32/dlgbox/common-dialog-box-library"
      type: "official"
    - title: "Windows File Dialog Forensics"
      url: "https://www.forensicfocus.com/articles/windows-file-dialog-forensics/"
      type: "research"

  retention:
    default_location: "Registry hive files (NTUSER.DAT)"
    persistence: "Dialog preferences persist until manually changed or application reinstallation"
    volatility: "Real-time updates with file dialog interactions and user customization"

  related_artifacts:
    - "opensavemru"
    - "lastvisited_pidlmru"
    - "acmru"
    - "shellbags"

author:
  name: "Tonmoy Jitu"
  github: "tonmoy0010"
  x: "tonmoy0010"

contribution:
  date_added: "2025-01-15"
  last_updated: "2025-01-15"
  version: "2.0"
